#!/usr/bin/env python3
import sys
import os

if len(sys.argv) < 2:
	print("./print_range [input file name] functions ...")
	exit(0)

# name of the input file
InputFileName = sys.argv[1]

# list of functions to modify
FunctionsList = sys.argv[2:]

# test if the input file exists
if not os.path.exists(InputFileName):
   	print("Input file not found")
   	exit(0)

f = open(InputFileName, 'r')

Lines = f.readlines()

CurrentFunction = ""
FullFunction = ""

for Line in Lines:
	Fields = Line.split()

	if len(Fields) == 12:
		CurrentFunction = Fields[0].split(sep="/")[1] + "/" + Fields[0].split(sep="/")[2]
		FullFunction = Fields[0]

	elif len(Fields) == 7:
		if CurrentFunction in FunctionsList:
			print(Fields[0], FullFunction, Fields[5], Fields[6])

	elif len(Fields) != 0:
		print("Wrong input file structure")
		exit(0)

f.close()