test_canc_detect: test_canc_detect.c
	gcc test_canc_detect.c -o test_canc_detect -Wall -O3 -ftree-vectorize

test_canc_exp: test_canc_exp.c
	gcc test_canc_exp.c -o test_canc_exp -Wall -O3 -ftree-vectorize

compare: compare.c
	gcc compare.c -o compare -Wall -O3 -ftree-vectorize