test_canc_detect: test_canc_detect.c
	clang test_canc_detect.c -o test_canc_detect -Wall -O3 -ftree-vectorize

test_canc_exp: test_canc_exp.c
	clang test_canc_exp.c -o test_canc_exp -Wall -O3 -ftree-vectorize

compare: compare.c
	clang compare.c -o compare -Wall -O3 -ftree-vectorize