#!/bin/sh
''''exec setarch -R python3 -u "$0" "$@" #'''
# This hack is an ugly but portable alternative to #!/usr/bin/env -S python3 -u
# we call setarch -R to disable ASLR, so that addresses during reference run
# always match addresses during sample runs (even for .so code).

import sys
import os
from verificarlo import dd_config
from verificarlo import DD_stoch
from verificarlo import DD_exec_stat

class DDline(DD_stoch.DDStoch):
    def __init__(self, config, prefix="dd.line"):
        DD_stoch.DDStoch.__init__(self, config, prefix)

    def referenceRunEnv(self):
        return {"VFC_BACKENDS": "libinterflop_ieee.so",
                "VFC_DDEBUG_GEN":   os.path.join(self.ref_,"dd.line.%%p")}

    def isFileValidToMerge(self, name):
        return name.startswith("dd.line.")

    def getDeltaFileName(self):
        return "dd.line"

    def sampleRunEnv(self,dirName):
        return {"VFC_DDEBUG_INCLUDE": os.path.join(dirName,self.getDeltaFileName() +".include")}

    def coerce(self, delta_config):
        return "\n".join([l[:-1] for l in delta_config])

if __name__ == "__main__":
    et=DD_exec_stat.exec_stat("dd.line")
    config=dd_config.ddConfig(sys.argv,os.environ)
    dd = DDline(config)
    dd.run()
    et.terminate()
